name: auryn
description: "AURYN Falante - AI Assistant"
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^3.0.7
  provider: ^6.1.1
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/data/
    - assets/hotword_models/
    - assets/images/
    - assets/memory/
    - assets/voice_models/
